import { generateReactKey } from "@/utils/id";
import type { RequestTemplate } from "./types";

// Templates from EUDIW Unfold interoperability event
// Source: https://verifier-playground.igrant.io/admin/presets/
// Note: age_verification_over_18 (av_mdoc) is skipped as it's not supported

export const EUDIW_UNFOLD_TEMPLATES: RequestTemplate[] = [
	// ── mDL (mdoc) templates ──────────────────────────────
	{
		id: "unfold-mdl-mdoc-all",
		name: "mDL (mdoc) — All Attributes",
		description: "Request all mDL attributes as ISO mdoc",
		category: "eudiw-unfold",
		credentialRequests: [
			{
				id: "unfold-mdl-mdoc-all-cred",
				documentType: "mdl",
				formatId: "mdl_mdoc",
				format: "mso_mdoc",
				attributes: [
					"family_name",
					"given_name",
					"birth_date",
					"issue_date",
					"expiry_date",
					"issuing_country",
					"issuing_authority",
					"document_number",
					"driving_privileges",
					"un_distinguishing_sign",
					"sex",
					"height",
					"weight",
					"eye_colour",
					"hair_colour",
					"birth_place",
					"resident_address",
					"age_over_18",
					"age_over_21",
					"issuing_jurisdiction",
				],
				reactKey: generateReactKey(),
			},
		],
		credentialSets: [],
		isBuiltIn: true,
	},
	{
		id: "unfold-mdl-mdoc-mandatory",
		name: "mDL (mdoc) — Mandatory",
		description: "Request mandatory mDL attributes as ISO mdoc",
		category: "eudiw-unfold",
		credentialRequests: [
			{
				id: "unfold-mdl-mdoc-mandatory-cred",
				documentType: "mdl",
				formatId: "mdl_mdoc",
				format: "mso_mdoc",
				attributes: [
					"family_name",
					"given_name",
					"birth_date",
					"issue_date",
					"expiry_date",
					"issuing_country",
					"issuing_authority",
					"document_number",
					"driving_privileges",
					"un_distinguishing_sign",
				],
				reactKey: generateReactKey(),
			},
		],
		credentialSets: [],
		isBuiltIn: true,
	},

	// ── EU PID (Any Format) templates ─────────────────────
	{
		id: "unfold-eu-pid-any-all",
		name: "EU PID (Any Format) — All Attributes",
		description:
			"Request all PID attributes; wallet chooses SD-JWT VC or mdoc format",
		category: "eudiw-unfold",
		credentialRequests: [
			{
				id: "unfold-eu-pid-any-all-sdjwt-cred",
				documentType: "pid",
				formatId: "pid_sd_jwt",
				format: "dc+sd-jwt",
				attributes: [
					"family_name",
					"given_name",
					"birth_date",
					"birth_place",
					"nationality",
					"expiry_date",
					"issuing_authority",
					"issuing_country",
					"resident_address",
					"resident_country",
					"resident_state",
					"resident_city",
					"resident_postal_code",
					"resident_street",
					"resident_house_number",
					"sex",
					"email_address",
					"document_number",
					"issuing_jurisdiction",
					"issuance_date",
				],
				reactKey: generateReactKey(),
			},
			{
				id: "unfold-eu-pid-any-all-mdoc-cred",
				documentType: "pid",
				formatId: "pid_mdoc",
				format: "mso_mdoc",
				attributes: [
					"family_name",
					"given_name",
					"birth_date",
					"birth_place",
					"nationality",
					"expiry_date",
					"issuing_authority",
					"issuing_country",
					"resident_address",
					"resident_country",
					"resident_state",
					"resident_city",
					"resident_postal_code",
					"resident_street",
					"resident_house_number",
					"sex",
					"email_address",
					"mobile_phone_number",
					"document_number",
					"issuing_jurisdiction",
					"issuance_date",
				],
				reactKey: generateReactKey(),
			},
		],
		credentialSets: [
			{
				id: "unfold-eu-pid-any-all-set",
				options: [
					["unfold-eu-pid-any-all-sdjwt-cred"],
					["unfold-eu-pid-any-all-mdoc-cred"],
				],
				required: true,
				reactKey: generateReactKey(),
			},
		],
		isBuiltIn: true,
	},
	{
		id: "unfold-eu-pid-any-mandatory",
		name: "EU PID (Any Format) — Mandatory",
		description:
			"Request mandatory PID attributes; wallet chooses SD-JWT VC or mdoc format",
		category: "eudiw-unfold",
		credentialRequests: [
			{
				id: "unfold-eu-pid-any-mandatory-sdjwt-cred",
				documentType: "pid",
				formatId: "pid_sd_jwt",
				format: "dc+sd-jwt",
				attributes: [
					"family_name",
					"given_name",
					"birth_date",
					"birth_place",
					"nationality",
					"expiry_date",
					"issuing_authority",
					"issuing_country",
				],
				reactKey: generateReactKey(),
			},
			{
				id: "unfold-eu-pid-any-mandatory-mdoc-cred",
				documentType: "pid",
				formatId: "pid_mdoc",
				format: "mso_mdoc",
				attributes: [
					"family_name",
					"given_name",
					"birth_date",
					"birth_place",
					"nationality",
					"expiry_date",
					"issuing_authority",
					"issuing_country",
				],
				reactKey: generateReactKey(),
			},
		],
		credentialSets: [
			{
				id: "unfold-eu-pid-any-mandatory-set",
				options: [
					["unfold-eu-pid-any-mandatory-sdjwt-cred"],
					["unfold-eu-pid-any-mandatory-mdoc-cred"],
				],
				required: true,
				reactKey: generateReactKey(),
			},
		],
		isBuiltIn: true,
	},

	// ── EU PID (mdoc) templates ───────────────────────────
	{
		id: "unfold-eu-pid-mdoc-all",
		name: "EU PID (mdoc) — All Attributes",
		description: "Request all PID attributes as ISO mdoc",
		category: "eudiw-unfold",
		credentialRequests: [
			{
				id: "unfold-eu-pid-mdoc-all-cred",
				documentType: "pid",
				formatId: "pid_mdoc",
				format: "mso_mdoc",
				attributes: [
					"family_name",
					"given_name",
					"birth_date",
					"birth_place",
					"nationality",
					"expiry_date",
					"issuing_authority",
					"issuing_country",
					"resident_address",
					"resident_country",
					"resident_state",
					"resident_city",
					"resident_postal_code",
					"resident_street",
					"resident_house_number",
					"sex",
					"email_address",
					"mobile_phone_number",
					"document_number",
					"issuing_jurisdiction",
					"issuance_date",
				],
				reactKey: generateReactKey(),
			},
		],
		credentialSets: [],
		isBuiltIn: true,
	},
	{
		id: "unfold-eu-pid-mdoc-mandatory",
		name: "EU PID (mdoc) — Mandatory",
		description: "Request mandatory PID attributes as ISO mdoc",
		category: "eudiw-unfold",
		credentialRequests: [
			{
				id: "unfold-eu-pid-mdoc-mandatory-cred",
				documentType: "pid",
				formatId: "pid_mdoc",
				format: "mso_mdoc",
				attributes: [
					"family_name",
					"given_name",
					"birth_date",
					"birth_place",
					"nationality",
					"expiry_date",
					"issuing_authority",
					"issuing_country",
				],
				reactKey: generateReactKey(),
			},
		],
		credentialSets: [],
		isBuiltIn: true,
	},

	// ── EU PID (SD-JWT VC) templates ──────────────────────
	{
		id: "unfold-eu-pid-sdjwt-all",
		name: "EU PID (SD-JWT VC) — All Attributes",
		description: "Request all PID attributes as SD-JWT VC",
		category: "eudiw-unfold",
		credentialRequests: [
			{
				id: "unfold-eu-pid-sdjwt-all-cred",
				documentType: "pid",
				formatId: "pid_sd_jwt",
				format: "dc+sd-jwt",
				attributes: [
					"family_name",
					"given_name",
					"birth_date",
					"birth_place",
					"nationality",
					"expiry_date",
					"issuing_authority",
					"issuing_country",
					"resident_address",
					"resident_country",
					"resident_state",
					"resident_city",
					"resident_postal_code",
					"resident_street",
					"resident_house_number",
					"sex",
					"email_address",
					"document_number",
					"issuing_jurisdiction",
					"issuance_date",
				],
				reactKey: generateReactKey(),
			},
		],
		credentialSets: [],
		isBuiltIn: true,
	},
	{
		id: "unfold-eu-pid-sdjwt-mandatory",
		name: "EU PID (SD-JWT VC) — Mandatory",
		description: "Request mandatory PID attributes as SD-JWT VC",
		category: "eudiw-unfold",
		credentialRequests: [
			{
				id: "unfold-eu-pid-sdjwt-mandatory-cred",
				documentType: "pid",
				formatId: "pid_sd_jwt",
				format: "dc+sd-jwt",
				attributes: [
					"family_name",
					"given_name",
					"birth_date",
					"birth_place",
					"nationality",
					"expiry_date",
					"issuing_authority",
					"issuing_country",
				],
				reactKey: generateReactKey(),
			},
		],
		credentialSets: [],
		isBuiltIn: true,
	},
];
